### ISSUE TITLE
missing timestamps when converting from depth-image to pointcloud

### ISSUE THREAD

**Issue by ganrok** [tud-pses/pses_kinect_filter#4]
When converting depth-msgs to pointclouds no timestamps are given. This can lead to timing problems with e.g. non static TF transformations.

The solution is adding a simple line in src/nodelets/point_cloud_xyz.cpp

Line 131 onwards: 

`pc->header.frame_id = tf_frame_;`
`pc->header.stamp = depth_msg->header.stamp.toNSec() / 1000ull;`
`pub_cloud_.publish(pc);`

**Comment by Nsteel** [comment]
Thanks for pointing that out!
